name: SB Engine workflow
on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  Desktop:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        sample: [debug, release]
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest

      - name: Installing Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libvlc-dev libvlccore-dev

      - name: Installing Haxe Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp 4.2.1 > /dev/null
          haxelib install lime 8.0.2
          haxelib install openfl 9.2.1
          haxelib install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib install tjson
          haxelib install hxjsonast
          haxelib install hxCodec 2.5.1
          haxelib install hscript
          haxelib install SScript 8.1.6
          haxelib install hxcpp-debug-server
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
      
      - name: Configure Desktop
        run: |
          haxelib set hxcpp 4.2.1
          haxelib set lime 8.0.2
          haxelib set openfl 9.2.1
          haxelib set SScript 8.1.6

      - name: List of installed Haxe Libraries
        run: haxelib list

      - name: Building Windows
        if: matrix.os == 'windows-latest'
        run: cd samples/${{matrix.sample}} && haxelib run lime build windows -debug

      - name: Building MacOS
        if: matrix.os == 'macos-latest'
        run: cd samples/${{matrix.sample}} && haxelib run lime build mac -debug

      - name: Building Linux
        if: matrix.os == 'ubuntu-latest'
        run: cd samples/${{matrix.sample}} && haxelib run lime build linux -debug

      - name: Upload Artifact Windows
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@main
        with:
          name: windowsBuild-${{matrix.sample}}
          path: samples/${{matrix.sample}}/export/windows/bin
          if-no-files-found: warn

      - name: Upload Artifact MacOS
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@main
        with:
          name: macBuild-${{matrix.sample}}
          path: samples/${{matrix.sample}}/export/macos/bin
          if-no-files-found: warn

      - name: Upload Artifact Linux
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@main
        with:
          name: linuxBuild-${{matrix.sample}}
          path: samples/${{matrix.sample}}/export/linux/bin
          if-no-files-found: warn
  Android:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sample: [debug, release]
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest

      - name: Installing Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib --quiet install hxcpp 4.2.1 > /dev/null
          haxelib --quiet install lime 8.0.2
          haxelib --quiet install openfl 9.2.1
          haxelib --quiet install flixel
          haxelib --quiet run lime setup flixel
          haxelib --quiet install flixel-tools
          haxelib --quiet install flixel-ui
          haxelib --quiet install flixel-addons
          haxelib --quiet install tjson
          haxelib --quiet install hxjsonast
          haxelib --quiet install SScript 8.1.6
          haxelib --quiet git hxCodec https://github.com/SPLCoding/hxCodec-but-it-works-xd.git
          haxelib --quiet git linc_luajit https://github.com/superpowers04/linc_luajit.git
          haxelib --quiet git extension-androidtools https://github.com/MaysLastPlay77/extension-androidtools.git
          haxelib --quiet git androiddialogs https://github.com/beihu235/AndroidDialogs
          haxelib --quiet git devicelanguage https://github.com/beihu235/devicelanguage

      - name: List of installed Haxe Libraries
        run: haxelib list

      - name: Configure Android
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_ROOT
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
          haxelib set hxcpp 4.2.1
          haxelib set lime 8.0.2
          haxelib set openfl 9.2.1
          haxelib set SScript 8.1.6

      - name: Building
        run: cd samples/${{matrix.sample}} && haxelib run lime build android -debug

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: androidBuild-${{matrix.sample}}
          path: samples/${{matrix.sample}}/export/android/bin/app/build/outputs/apk/debug
          if-no-files-found: warn